package modelo;
// Generated 30/10/2015 12:28:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Camion generated by hbm2java
 */
public class Camion  implements java.io.Serializable {


     private Integer idCamion;
     private TipoCamion tipoCamion;
     private String placa;
     private Date fechaRegistro;
     private String estado;
     private Set mantenimientos = new HashSet(0);
     private Set rutas = new HashSet(0);
     private Set disponibilidads = new HashSet(0);

    public Camion() {
    }

	
    public Camion(TipoCamion tipoCamion, String placa, Date fechaRegistro, String estado) {
        this.tipoCamion = tipoCamion;
        this.placa = placa;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
    }
    public Camion(TipoCamion tipoCamion, String placa, Date fechaRegistro, String estado, Set mantenimientos, Set rutas, Set disponibilidads) {
       this.tipoCamion = tipoCamion;
       this.placa = placa;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.mantenimientos = mantenimientos;
       this.rutas = rutas;
       this.disponibilidads = disponibilidads;
    }
   
    public Integer getIdCamion() {
        return this.idCamion;
    }
    
    public void setIdCamion(Integer idCamion) {
        this.idCamion = idCamion;
    }
    public TipoCamion getTipoCamion() {
        return this.tipoCamion;
    }
    
    public void setTipoCamion(TipoCamion tipoCamion) {
        this.tipoCamion = tipoCamion;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }
    public Set getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Set rutas) {
        this.rutas = rutas;
    }
    public Set getDisponibilidads() {
        return this.disponibilidads;
    }
    
    public void setDisponibilidads(Set disponibilidads) {
        this.disponibilidads = disponibilidads;
    }




}


