package Modelo.Hibernate;
// Generated 02/11/2015 06:39:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Accidente generated by hbm2java
 */
public class Accidente  implements java.io.Serializable {


     private Integer idAccidente;
     private Nodo nodo;
     private Ruta ruta;
     private Date fecha;
     private Date hora;
     private String estado;
     private String observacion;
     private String solucion;

    public Accidente() {
    }

	
    public Accidente(Nodo nodo, Date fecha, Date hora, String estado) {
        this.nodo = nodo;
        this.fecha = fecha;
        this.hora = hora;
        this.estado = estado;
    }
    public Accidente(Nodo nodo, Ruta ruta, Date fecha, Date hora, String estado, String observacion, String solucion) {
       this.nodo = nodo;
       this.ruta = ruta;
       this.fecha = fecha;
       this.hora = hora;
       this.estado = estado;
       this.observacion = observacion;
       this.solucion = solucion;
    }
   
    public Integer getIdAccidente() {
        return this.idAccidente;
    }
    
    public void setIdAccidente(Integer idAccidente) {
        this.idAccidente = idAccidente;
    }
    public Nodo getNodo() {
        return this.nodo;
    }
    
    public void setNodo(Nodo nodo) {
        this.nodo = nodo;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getSolucion() {
        return this.solucion;
    }
    
    public void setSolucion(String solucion) {
        this.solucion = solucion;
    }




}


