package Modelo.Hibernate;
// Generated 10/11/2015 08:33:55 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Camion generated by hbm2java
 */
public class Camion  implements java.io.Serializable {


     private Integer idCamion;
     private TipoCamion tipoCamion;
     private String placa;
     private Date fechaRegistro;
     private String estado;
     private List<Mantenimiento> mantenimientos = new ArrayList<Mantenimiento>();
     private List<Ruta> rutas = new ArrayList<Ruta>();
     private List<Disponibilidad> disponibilidads = new ArrayList<Disponibilidad>();
	 

    public Camion() {
    }

    public Camion(TipoCamion tipoCamion, String estado){
        this.disponibilidads = new ArrayList<Disponibilidad>(); 
        this.tipoCamion = tipoCamion;
        this.estado = estado;
    }
	
    public Camion(TipoCamion tipoCamion, String placa, Date fechaRegistro, String estado) {
        this.tipoCamion = tipoCamion;
        this.placa = placa;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
    }
    public Camion(TipoCamion tipoCamion, String placa, Date fechaRegistro, String estado, 
            List<Mantenimiento> mantenimientos, List<Ruta> rutas, List<Disponibilidad> disponibilidads) {
       this.tipoCamion = tipoCamion;
       this.placa = placa;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.mantenimientos = mantenimientos;
       this.rutas = rutas;
       this.disponibilidads = disponibilidads;
    }
   
    public Integer getIdCamion() {
        return this.idCamion;
    }
    
    public void setIdCamion(Integer idCamion) {
        this.idCamion = idCamion;
    }
    public TipoCamion getTipoCamion() {
        return this.tipoCamion;
    }
    
    public void setTipoCamion(TipoCamion tipoCamion) {
        this.tipoCamion = tipoCamion;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    public List getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(List<Mantenimiento> mantenimientos) {
        this.mantenimientos = mantenimientos;
    }
    public List getRutas() {
        return this.rutas;
    }
    
    public void setRutas(List<Ruta> rutas) {
        this.rutas = rutas;
    }
    public List getDisponibilidads() {
        return this.disponibilidads;
    }
    
    public void setDisponibilidads(List<Disponibilidad> disponibilidads) {
        this.disponibilidads = disponibilidads;
    }




}


