package Modelo.Hibernate;
// Generated 10/11/2015 08:33:55 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Disponibilidad generated by hbm2java
 */
public class Disponibilidad  implements java.io.Serializable {


     private Integer idDisponibilidad;
     private Camion camion;
     private Date horaInicio;
     private Date horaFin;
     private Date fecha;

    public Disponibilidad() {
    }

    public Disponibilidad(Camion camion, Date horaInicio, Date horaFin, Date fecha) {
       this.camion = camion;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.fecha = fecha;
    }
   
    public Integer getIdDisponibilidad() {
        return this.idDisponibilidad;
    }
    
    public void setIdDisponibilidad(Integer idDisponibilidad) {
        this.idDisponibilidad = idDisponibilidad;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


