package Modelo.Hibernate;
// Generated 10/11/2015 08:33:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Turno turno;
     private Date fechaRegistro;
     private String estado;
     private String puesto;
     private String nombres;
     private String apellidoPat;
     private String apellidoMat;
     private String dni;
     private Set rutasForIdCopiloto = new HashSet(0);
     private Set rutasForIdConductor = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Turno turno, Date fechaRegistro, String estado, String puesto, String nombres, String apellidoPat, String apellidoMat, String dni) {
        this.turno = turno;
        this.fechaRegistro = fechaRegistro;
        this.estado = estado;
        this.puesto = puesto;
        this.nombres = nombres;
        this.apellidoPat = apellidoPat;
        this.apellidoMat = apellidoMat;
        this.dni = dni;
    }
    public Empleado(Turno turno, Date fechaRegistro, String estado, String puesto, String nombres, String apellidoPat, String apellidoMat, String dni, Set rutasForIdCopiloto, Set rutasForIdConductor, Set usuarios) {
       this.turno = turno;
       this.fechaRegistro = fechaRegistro;
       this.estado = estado;
       this.puesto = puesto;
       this.nombres = nombres;
       this.apellidoPat = apellidoPat;
       this.apellidoMat = apellidoMat;
       this.dni = dni;
       this.rutasForIdCopiloto = rutasForIdCopiloto;
       this.rutasForIdConductor = rutasForIdConductor;
       this.usuarios = usuarios;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidoPat() {
        return this.apellidoPat;
    }
    
    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }
    public String getApellidoMat() {
        return this.apellidoMat;
    }
    
    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Set getRutasForIdCopiloto() {
        return this.rutasForIdCopiloto;
    }
    
    public void setRutasForIdCopiloto(Set rutasForIdCopiloto) {
        this.rutasForIdCopiloto = rutasForIdCopiloto;
    }
    public Set getRutasForIdConductor() {
        return this.rutasForIdConductor;
    }
    
    public void setRutasForIdConductor(Set rutasForIdConductor) {
        this.rutasForIdConductor = rutasForIdConductor;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


