package Modelo.Hibernate;
// Generated 10/11/2015 08:33:55 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer idRuta;
     private Camion camion;
     private Empleado empleadoByIdCopiloto;
     private Empleado empleadoByIdConductor;
     private Date fechaEntrega;
     private Date horaSalida;
     private Date horaLlegada;
     private int cantGlp;
     private int cantDiesel;
     private int distancia;
     private int diffTiempo;
     private List<Arista> aristas = new ArrayList<Arista>();
     private Set accidentes = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(Camion camion, Empleado empleadoByIdConductor, Date fechaEntrega, Date horaSalida, int cantGlp, int cantDiesel, int distancia, int diffTiempo) {
        this.camion = camion;
        this.empleadoByIdConductor = empleadoByIdConductor;
        this.fechaEntrega = fechaEntrega;
        this.horaSalida = horaSalida;
        this.cantGlp = cantGlp;
        this.cantDiesel = cantDiesel;
        this.distancia = distancia;
        this.diffTiempo = diffTiempo;
    }
    public Ruta(Camion camion, Empleado empleadoByIdCopiloto, Empleado empleadoByIdConductor, 
            Date fechaEntrega, Date horaSalida, Date horaLlegada, int cantGlp, int cantDiesel, 
            int distancia, int diffTiempo, List<Arista> aristas, Set accidentes) {
       this.camion = camion;
       this.empleadoByIdCopiloto = empleadoByIdCopiloto;
       this.empleadoByIdConductor = empleadoByIdConductor;
       this.fechaEntrega = fechaEntrega;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.cantGlp = cantGlp;
       this.cantDiesel = cantDiesel;
       this.distancia = distancia;
       this.diffTiempo = diffTiempo;
       this.aristas = aristas;
       this.accidentes = accidentes;
    }
   
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public Empleado getEmpleadoByIdCopiloto() {
        return this.empleadoByIdCopiloto;
    }
    
    public void setEmpleadoByIdCopiloto(Empleado empleadoByIdCopiloto) {
        this.empleadoByIdCopiloto = empleadoByIdCopiloto;
    }
    public Empleado getEmpleadoByIdConductor() {
        return this.empleadoByIdConductor;
    }
    
    public void setEmpleadoByIdConductor(Empleado empleadoByIdConductor) {
        this.empleadoByIdConductor = empleadoByIdConductor;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public int getCantGlp() {
        return this.cantGlp;
    }
    
    public void setCantGlp(int cantGlp) {
        this.cantGlp = cantGlp;
    }
    public int getCantDiesel() {
        return this.cantDiesel;
    }
    
    public void setCantDiesel(int cantDiesel) {
        this.cantDiesel = cantDiesel;
    }
    public int getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(int distancia) {
        this.distancia = distancia;
    }
    public int getDiffTiempo() {
        return this.diffTiempo;
    }
    
    public void setDiffTiempo(int diffTiempo) {
        this.diffTiempo = diffTiempo;
    }
    public List<Arista> getAristas() {
        return this.aristas;
    }
    
    public void setAristas(List<Arista> aristas) {
        this.aristas = aristas;
    }
    public Set getAccidentes() {
        return this.accidentes;
    }
    
    public void setAccidentes(Set accidentes) {
        this.accidentes = accidentes;
    }




}


