/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ClienteControlador;
import Controlador.GeneralControlador;
import Controlador.PedidoControlador;
import Modelo.Hibernate.Cliente;
import Modelo.Hibernate.Nodo;
import Modelo.Hibernate.Pedido;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author alulab14
 */
public class Pantalla_Pedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFramePedido
     */
    public Pantalla_Pedido() {
        initComponents();
        PedidoControlador.ActualizaTablaPedidos(PedidoControlador.ListarPedidos(), bPedTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPedidos = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        label17 = new java.awt.Label();
        jPanel38 = new javax.swing.JPanel();
        nPedNroDocText = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        nPedDirComboBox = new javax.swing.JComboBox();
        nPedNombCompText = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        nPedTipoDocComboBox = new javax.swing.JComboBox();
        nPedBuscCliBoton = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();
        nPedPlaMaxComboBox = new javax.swing.JComboBox();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        nPedVolText = new javax.swing.JSpinner();
        nPedNuevBoton = new javax.swing.JButton();
        nPedElimBoton = new javax.swing.JButton();
        nPedEditBoton = new javax.swing.JButton();
        nPedGuardBoton = new javax.swing.JButton();
        nPedCancelBoton = new javax.swing.JButton();
        nPedCargaBoton = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        label18 = new java.awt.Label();
        jPanel41 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        bPedNombText = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        bPedNroDocText = new javax.swing.JTextField();
        bPedTipoDocComboBox = new javax.swing.JComboBox();
        jPanel42 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        bPedBuscBoton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        bPedTabla = new javax.swing.JTable();
        jPanel44 = new javax.swing.JPanel();
        bPedPlazoComboBox = new javax.swing.JComboBox();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        bPedVolText = new javax.swing.JSpinner();
        jLabel100 = new javax.swing.JLabel();
        bPedEstadoComboBox = new javax.swing.JComboBox();

        panelPedidos.setBackground(new java.awt.Color(240, 240, 225));

        jPanel37.setBackground(new java.awt.Color(240, 240, 225));
        jPanel37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel37.setPreferredSize(new java.awt.Dimension(400, 620));

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label17.setForeground(new java.awt.Color(51, 0, 102));
        label17.setText("Pedido");

        jPanel38.setBackground(new java.awt.Color(240, 240, 225));
        jPanel38.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel38.setPreferredSize(new java.awt.Dimension(360, 250));

        nPedNroDocText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedNroDocTextActionPerformed(evt);
            }
        });

        jLabel83.setText("Nombre Completo:");

        jLabel85.setText("Tipo Documento:");

        jLabel86.setText("N° Documento:");

        nPedDirComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedDirComboBoxActionPerformed(evt);
            }
        });

        nPedNombCompText.setEnabled(false);
        nPedNombCompText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedNombCompTextActionPerformed(evt);
            }
        });

        jLabel87.setText("Dirección:");

        nPedTipoDocComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "RUC" }));
        nPedTipoDocComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedTipoDocComboBoxActionPerformed(evt);
            }
        });

        nPedBuscCliBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedBuscCliBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_buscar.png"))); // NOI18N
        nPedBuscCliBoton.setText("Buscar Cliente");
        nPedBuscCliBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedBuscCliBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel85)
                            .addComponent(jLabel86)
                            .addComponent(jLabel87)
                            .addComponent(jLabel83))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nPedTipoDocComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nPedNroDocText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nPedNombCompText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nPedDirComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nPedBuscCliBoton)))
                .addContainerGap())
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(nPedTipoDocComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nPedNroDocText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel86))
                .addGap(18, 18, 18)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(nPedNombCompText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nPedDirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel87))
                .addGap(18, 18, 18)
                .addComponent(nPedBuscCliBoton)
                .addGap(30, 30, 30))
        );

        jPanel39.setBackground(new java.awt.Color(240, 240, 225));
        jPanel39.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        nPedPlaMaxComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2 horas", "4 horas", "6 horas", "8 horas", "10 horas", "12 horas", "14 horas", "16 horas", "18 horas", "20 horas", "22 horas", "24 horas" }));
        nPedPlaMaxComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedPlaMaxComboBoxActionPerformed(evt);
            }
        });

        jLabel88.setText("Plazo máximo:");

        jLabel89.setText("Volumen (Ton):");

        nPedVolText.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.5d));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel88)
                    .addComponent(jLabel89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nPedPlaMaxComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nPedVolText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(nPedVolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(nPedPlaMaxComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        nPedNuevBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedNuevBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_nuevo.png"))); // NOI18N
        nPedNuevBoton.setText("Nuevo");
        nPedNuevBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedNuevBotonActionPerformed(evt);
            }
        });

        nPedElimBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedElimBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_eliminar.png"))); // NOI18N
        nPedElimBoton.setText("Eliminar");
        nPedElimBoton.setEnabled(false);
        nPedElimBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedElimBotonActionPerformed(evt);
            }
        });

        nPedEditBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedEditBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_editar.png"))); // NOI18N
        nPedEditBoton.setText("Editar");
        nPedEditBoton.setEnabled(false);
        nPedEditBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedEditBotonActionPerformed(evt);
            }
        });

        nPedGuardBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedGuardBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_guardar.png"))); // NOI18N
        nPedGuardBoton.setText("Guardar");
        nPedGuardBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedGuardBotonActionPerformed(evt);
            }
        });

        nPedCancelBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedCancelBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_cancelar.png"))); // NOI18N
        nPedCancelBoton.setText("Cancelar");
        nPedCancelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedCancelBotonActionPerformed(evt);
            }
        });

        nPedCargaBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nPedCargaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_editar.png"))); // NOI18N
        nPedCargaBoton.setText("Cargar");
        nPedCargaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedCargaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addComponent(nPedCancelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nPedGuardBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel37Layout.createSequentialGroup()
                                .addComponent(nPedElimBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nPedEditBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nPedCargaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(nPedNuevBoton)))
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nPedNuevBoton)
                        .addComponent(nPedCargaBoton))
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nPedElimBoton)
                    .addComponent(nPedEditBoton))
                .addGap(18, 18, 18)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nPedGuardBoton)
                    .addComponent(nPedCancelBoton))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jPanel40.setBackground(new java.awt.Color(240, 240, 225));
        jPanel40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel40.setPreferredSize(new java.awt.Dimension(750, 620));

        label18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label18.setForeground(new java.awt.Color(51, 0, 102));
        label18.setText("Buscar Pedido");

        jPanel41.setBackground(new java.awt.Color(240, 240, 225));
        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel41.setForeground(new java.awt.Color(250, 250, 225));
        jPanel41.setPreferredSize(new java.awt.Dimension(340, 250));

        jLabel91.setText("Nombre:");

        bPedNombText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedNombTextActionPerformed(evt);
            }
        });

        jLabel92.setText("Tipo Documento:");

        jLabel93.setText("N° Documento:");

        bPedNroDocText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedNroDocTextActionPerformed(evt);
            }
        });

        bPedTipoDocComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "DNI", "RUC" }));
        bPedTipoDocComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedTipoDocComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel92)
                    .addComponent(jLabel91)
                    .addComponent(jLabel93))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPedNombText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPedTipoDocComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPedNroDocText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(bPedNombText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(bPedTipoDocComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPedNroDocText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel93))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel42.setBackground(new java.awt.Color(240, 240, 225));
        jPanel42.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Entrega"));
        jPanel42.setPreferredSize(new java.awt.Dimension(340, 120));
        jPanel42.setRequestFocusEnabled(false);

        jLabel94.setText("Desde:");

        jLabel95.setText("Hasta:");

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel94)
                .addGap(32, 32, 32)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel95)
                .addGap(32, 32, 32)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel95)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel94)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        bPedBuscBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bPedBuscBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_buscar.png"))); // NOI18N
        bPedBuscBoton.setText("Buscar");
        bPedBuscBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedBuscBotonActionPerformed(evt);
            }
        });

        bPedTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Dirección", "Entrega Programada", "Volumen (Ton)", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bPedTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPedTablaMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(bPedTabla);
        if (bPedTabla.getColumnModel().getColumnCount() > 0) {
            bPedTabla.getColumnModel().getColumn(0).setResizable(false);
            bPedTabla.getColumnModel().getColumn(1).setResizable(false);
            bPedTabla.getColumnModel().getColumn(2).setResizable(false);
            bPedTabla.getColumnModel().getColumn(3).setResizable(false);
            bPedTabla.getColumnModel().getColumn(4).setResizable(false);
            bPedTabla.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel44.setBackground(new java.awt.Color(240, 240, 225));
        jPanel44.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel44.setPreferredSize(new java.awt.Dimension(340, 103));
        jPanel44.setVerifyInputWhenFocusTarget(false);

        bPedPlazoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "2 horas", "4 horas", "6 horas", "8 horas", "10 horas", "12 horas", "14 horas", "16 horas", "18 horas", "20 horas", "22 horas", "24 horas" }));
        bPedPlazoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedPlazoComboBoxActionPerformed(evt);
            }
        });

        jLabel98.setText("Plazo máximo:");

        jLabel99.setText("Menor a (Ton):");

        bPedVolText.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.5d));

        jLabel100.setText("Estado:");

        bPedEstadoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "ACTIVO", "ANULADO", "ENTREGADO" }));
        bPedEstadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedEstadoComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel99)
                    .addComponent(jLabel98)
                    .addComponent(jLabel100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPedEstadoComboBox, 0, 180, Short.MAX_VALUE)
                    .addComponent(bPedPlazoComboBox, 0, 180, Short.MAX_VALUE)
                    .addComponent(bPedVolText))
                .addGap(20, 20, 20))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bPedVolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel99))
                .addGap(18, 18, 18)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel98)
                    .addComponent(bPedPlazoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel100)
                    .addComponent(bPedEstadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(label18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPedBuscBoton))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel40Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPedBuscBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPedidosLayout = new javax.swing.GroupLayout(panelPedidos);
        panelPedidos.setLayout(panelPedidosLayout);
        panelPedidosLayout.setHorizontalGroup(
            panelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPedidosLayout.setVerticalGroup(
            panelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                    .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1309, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(panelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(panelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nPedNroDocTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedNroDocTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedNroDocTextActionPerformed

    private void nPedDirComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedDirComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedDirComboBoxActionPerformed

    private void nPedNombCompTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedNombCompTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedNombCompTextActionPerformed

    private void nPedTipoDocComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedTipoDocComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedTipoDocComboBoxActionPerformed

    private void nPedBuscCliBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedBuscCliBotonActionPerformed

        if (nPedNroDocText.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "El campo N° Documento está vacío");
        } else if (nPedTipoDocComboBox.getSelectedItem().toString().equalsIgnoreCase("DNI") && nPedNroDocText.getText().length() != 8) {
            JOptionPane.showMessageDialog(null, "Número de DNI debe tener 8 dígitos");
        } else if (nPedTipoDocComboBox.getSelectedItem().toString().equalsIgnoreCase("RUC") && nPedNroDocText.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "Número RUC debe tener 11 dígitos");
        } else if (!GeneralControlador.VerificaNroDoc(nPedNroDocText.getText())) {
            JOptionPane.showMessageDialog(null, "El número de documento solo debe contener dígitos");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            ArrayList<Cliente> nc = ClienteControlador.BuscaClienteNroDoc(nPedNroDocText.getText());
            this.setCursor(Cursor.getDefaultCursor());

            if (nc.size() > 0) {
                nPedNombCompText.setText(nc.get(0).getNombres());

                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                ArrayList<String> ls = GeneralControlador.ObtenListaDirecciones(nPedNroDocText);
                nPedDirComboBox.setModel(new DefaultComboBoxModel(ls.toArray()));
                this.setCursor(Cursor.getDefaultCursor());
            } else {
                JOptionPane.showMessageDialog(null, "El cliente no se encuentra registrado");
            }
        }

    }//GEN-LAST:event_nPedBuscCliBotonActionPerformed

    private void nPedPlaMaxComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedPlaMaxComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedPlaMaxComboBoxActionPerformed

    private void nPedNuevBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedNuevBotonActionPerformed
        DatosEditables(true);
        BotonesEditables(true);
        LimpiaCamposNuevoPedido();
    }//GEN-LAST:event_nPedNuevBotonActionPerformed

    private void LimpiaCamposNuevoPedido() {
        nPedNroDocText.setText("");
        nPedNombCompText.setText("");
        nPedVolText.setValue(0);
        nPedTipoDocComboBox.setSelectedItem("DNI");
        nPedPlaMaxComboBox.setSelectedItem("2 horas");
        nPedDirComboBox.setModel(new DefaultComboBoxModel());
    }

    private void nPedElimBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedElimBotonActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el registro");
        if (confirmacion == 0) {
            int fila = bPedTabla.getSelectedRow();
            String strCodigo = bPedTabla.getValueAt(fila, 0).toString();
            Integer codigo = Integer.parseInt(strCodigo);
            PedidoControlador.EliminarPedido(codigo);
            JOptionPane.showMessageDialog(null, "Se anuló el pedido correctamente");
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DatosEditables(true);
            BotonesEditables(true);
            LimpiaCamposNuevoPedido();
            PedidoControlador.ActualizaTablaPedidos(PedidoControlador.ListarPedidos(), bPedTabla);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_nPedElimBotonActionPerformed

    private void nPedEditBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedEditBotonActionPerformed
        nPedVolText.setEnabled(true);
        nPedPlaMaxComboBox.setEnabled(true);
        nPedElimBoton.setEnabled(false);
        nPedEditBoton.setEnabled(false);
        nPedCancelBoton.setEnabled(true);
        nPedGuardBoton.setEnabled(true);
    }//GEN-LAST:event_nPedEditBotonActionPerformed

    private void nPedGuardBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedGuardBotonActionPerformed
        if (nPedNroDocText.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "El campo N° Documento está vacío");
        } else if (nPedTipoDocComboBox.getSelectedItem().toString().equalsIgnoreCase("DNI") && nPedNroDocText.getText().length() != 8) {
            JOptionPane.showMessageDialog(null, "Número de DNI debe tener 8 dígitos");
        } else if (nPedTipoDocComboBox.getSelectedItem().toString().equalsIgnoreCase("RUC") && nPedNroDocText.getText().length() != 11) {
            JOptionPane.showMessageDialog(null, "Número RUC debe tener 11 dígitos");
        } else if (!GeneralControlador.VerificaNroDoc(nPedNroDocText.getText())) {
            JOptionPane.showMessageDialog(null, "El número de documento solo debe contener números");
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            ArrayList<Cliente> nc = ClienteControlador.BuscaClienteNroDoc(nPedNroDocText.getText());
            this.setCursor(Cursor.getDefaultCursor());

            if (nc.size() > 0) {

                if (!nc.get(0).getNombres().equalsIgnoreCase(nPedNombCompText.getText())) {
                    JOptionPane.showMessageDialog(null, "El número de documento del cliente, se han actualizado los datos.\nPor favor seleccione correctamente");
                    nPedNombCompText.setText(nc.get(0).getNombres());

                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    ArrayList<String> ls = GeneralControlador.ObtenListaDirecciones(nPedNroDocText);
                    nPedDirComboBox.setModel(new DefaultComboBoxModel(ls.toArray()));
                    this.setCursor(Cursor.getDefaultCursor());

                } else {
                    if (nPedVolText.getValue().toString().equalsIgnoreCase("0")) {
                        JOptionPane.showMessageDialog(null, "No se puede registrar un pedido con 0 toneladas solicitadas");
                    } else {
                        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        ArrayList<Integer> aux = GeneralControlador.SacaCoordinadas(nPedDirComboBox.getSelectedItem().toString());
                        Cliente c = ClienteControlador.BuscaClienteDireccion(nc, aux);
                        int p = GeneralControlador.SacaSiguienteNumeroEnString(nPedPlaMaxComboBox.getSelectedItem().toString());
                        double cantGLP = Double.parseDouble(nPedVolText.getValue().toString());

                        Pedido ped;

                        int fila = bPedTabla.getSelectedRow();

                        if (fila != -1) { //que una fila de la tabla está seleccionada
                            String strCodigo = bPedTabla.getValueAt(fila, 0).toString();
                            int pedidoId = Integer.parseInt(strCodigo);
                            ped = PedidoControlador.BuscaPedidoId(pedidoId);

                            ped.setCantGlp(cantGLP);

                            Calendar cal = Calendar.getInstance();
                            cal.setTime(ped.getFechaRegistro());
                            cal.add(Calendar.HOUR, p);
                            Date horaSol = cal.getTime();

                            ped.setHoraSolicitada(horaSol);
                        } else {
                            String prioridad;

                            if (PedidoControlador.TienePrioridad(c)) {
                                prioridad = "SI";
                            } else {
                                prioridad = "NO";
                            }

                            Calendar cal = Calendar.getInstance(); //fecha y hora actual de registro
                            Date ahora = cal.getTime();
                            cal.add(Calendar.HOUR, p);
                            Date horaSol = cal.getTime();

                            ped = new Pedido(c, ahora, horaSol, cantGLP, p, prioridad);
                        }

                        PedidoControlador.GuardarPedido(ped);
                        this.setCursor(Cursor.getDefaultCursor());
                        JOptionPane.showMessageDialog(null, "Se registró el pedido correctamente");
                        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        DatosEditables(true);
                        BotonesEditables(true);
                        LimpiaCamposNuevoPedido();
                        PedidoControlador.ActualizaTablaPedidos(PedidoControlador.ListarPedidos(), bPedTabla);
                        this.setCursor(Cursor.getDefaultCursor());
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "El cliente no se encuentra registrado");
            }
        }
    }//GEN-LAST:event_nPedGuardBotonActionPerformed

    private void nPedCancelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedCancelBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedCancelBotonActionPerformed

    private void bPedNombTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedNombTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPedNombTextActionPerformed

    private void bPedNroDocTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedNroDocTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPedNroDocTextActionPerformed

    private void bPedTipoDocComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedTipoDocComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPedTipoDocComboBoxActionPerformed

    private void bPedBuscBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedBuscBotonActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        ArrayList<Pedido> lista = PedidoControlador.BuscaPedidosFiltro(bPedNombText, bPedTipoDocComboBox, bPedNroDocText, bPedVolText, bPedPlazoComboBox, bPedEstadoComboBox);
        PedidoControlador.ActualizaTablaPedidos(lista, bPedTabla);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_bPedBuscBotonActionPerformed

    private void bPedPlazoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedPlazoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPedPlazoComboBoxActionPerformed

    private void bPedTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPedTablaMouseClicked
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        int fila = bPedTabla.getSelectedRow();
        VerDatos(bPedTabla.getValueAt(fila, 0).toString());
        DatosEditables(false);
        BotonesEditables(false);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_bPedTablaMouseClicked

    private void nPedCargaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedCargaBotonActionPerformed
        
        nPedCargaBoton.setEnabled(false);
        File archivo = GeneralControlador.obtenerArchivo();
        if(archivo!=null){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            PedidoControlador.CargaPedidosArchivo(archivo.getAbsolutePath());
            this.setCursor(Cursor.getDefaultCursor());
            JOptionPane.showMessageDialog(null, "Se cargaron los pedidos correctamente");
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        PedidoControlador.ActualizaTablaPedidos(PedidoControlador.ListarPedidos(), bPedTabla);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_nPedCargaBotonActionPerformed

    private void bPedEstadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedEstadoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPedEstadoComboBoxActionPerformed

    private void VerDatos(String strCodigo) {
        int pedidoId = Integer.parseInt(strCodigo);
        Pedido ped = PedidoControlador.BuscaPedidoId(pedidoId);

        String plazoAux = "" + ped.getPlazo() + " horas";
        String dirAux = GeneralControlador.DevuelveFormatoDireccion(ped.getCliente().getNodo().getCoordX(), ped.getCliente().getNodo().getCoordY());

        nPedNroDocText.setText(ped.getCliente().getNroDocumento());
        nPedNombCompText.setText(ped.getCliente().getNombres());
        nPedVolText.setValue(ped.getCantGlp());
        nPedTipoDocComboBox.setSelectedItem(ped.getCliente().getTipoDocumento());
        nPedPlaMaxComboBox.setSelectedItem(plazoAux);

        ArrayList<String> ls = GeneralControlador.ObtenListaDirecciones(nPedNroDocText);
        nPedDirComboBox.setModel(new DefaultComboBoxModel(ls.toArray()));

        nPedDirComboBox.setSelectedItem(dirAux);
    }

    private void DatosEditables(boolean valor) {
        nPedNroDocText.setEnabled(valor);
        nPedVolText.setEnabled(valor);
        nPedTipoDocComboBox.setEnabled(valor);
        nPedPlaMaxComboBox.setEnabled(valor);
        nPedDirComboBox.setEnabled(valor);
    }

    private void BotonesEditables(boolean valor) {
        nPedBuscCliBoton.setEnabled(valor);
        nPedElimBoton.setEnabled(!valor);
        nPedEditBoton.setEnabled(!valor);
        nPedCancelBoton.setEnabled(valor);
        nPedGuardBoton.setEnabled(valor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPedBuscBoton;
    private javax.swing.JComboBox bPedEstadoComboBox;
    private javax.swing.JTextField bPedNombText;
    private javax.swing.JTextField bPedNroDocText;
    private javax.swing.JComboBox bPedPlazoComboBox;
    private javax.swing.JTable bPedTabla;
    private javax.swing.JComboBox bPedTipoDocComboBox;
    private javax.swing.JSpinner bPedVolText;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JScrollPane jScrollPane9;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private javax.swing.JButton nPedBuscCliBoton;
    private javax.swing.JButton nPedCancelBoton;
    private javax.swing.JButton nPedCargaBoton;
    private javax.swing.JComboBox nPedDirComboBox;
    private javax.swing.JButton nPedEditBoton;
    private javax.swing.JButton nPedElimBoton;
    private javax.swing.JButton nPedGuardBoton;
    private javax.swing.JTextField nPedNombCompText;
    private javax.swing.JTextField nPedNroDocText;
    private javax.swing.JButton nPedNuevBoton;
    private javax.swing.JComboBox nPedPlaMaxComboBox;
    private javax.swing.JComboBox nPedTipoDocComboBox;
    private javax.swing.JSpinner nPedVolText;
    private javax.swing.JPanel panelPedidos;
    // End of variables declaration//GEN-END:variables
}
