/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import Controlador.ClienteControlador;
import Modelo.Constantes.EasyGas;
import Modelo.Hibernate.Cliente;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.query.JRHibernateQueryExecuterFactory;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.digester.Digester; 
import org.hibernate.Transaction;
import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
//import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
/**
 *
 * @author Mariella
 */
public class Pantalla_PedidosPorCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pantalla_ReportePrueba
     */
    ClienteControlador clienteControlador= new ClienteControlador();
    public Pantalla_PedidosPorCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the F     orm Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManten = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        cmbCamionBuscarTipo = new javax.swing.JComboBox();
        txtCamionBuscarPlaca = new javax.swing.JTextField();
        cmbCamionBuscarEstado = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        label13 = new java.awt.Label();
        jPanel41 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        dtFechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        dtFechaHasta = new com.toedter.calendar.JDateChooser();

        panelManten.setBackground(new java.awt.Color(240, 240, 225));
        panelManten.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Camión"));
        panelManten.setPreferredSize(new java.awt.Dimension(340, 125));

        jLabel73.setText("Estado");

        jLabel70.setText("Tipo de Camión:");

        jLabel80.setText("Placa:");

        cmbCamionBuscarTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));

        cmbCamionBuscarEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Disponible", "En curso", "En mantenimiento", "De regreso" }));

        javax.swing.GroupLayout panelMantenLayout = new javax.swing.GroupLayout(panelManten);
        panelManten.setLayout(panelMantenLayout);
        panelMantenLayout.setHorizontalGroup(
            panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMantenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70)
                    .addComponent(jLabel80)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCamionBuscarTipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCamionBuscarPlaca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCamionBuscarEstado, 0, 180, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        panelMantenLayout.setVerticalGroup(
            panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCamionBuscarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70))
                .addGap(18, 18, 18)
                .addGroup(panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(txtCamionBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(cmbCamionBuscarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(240, 240, 225));

        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_generar.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label13.setForeground(new java.awt.Color(51, 0, 102));
        label13.setText("Pedidos Por Cliente");

        jPanel41.setBackground(new java.awt.Color(240, 240, 225));
        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros"));
        jPanel41.setForeground(new java.awt.Color(250, 250, 225));
        jPanel41.setPreferredSize(new java.awt.Dimension(340, 250));

        jLabel93.setText("N° Documento:");

        jLabel94.setText("Fecha Desde:");

        jLabel95.setText("Fecha Hasta:");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel93)
                    .addComponent(jLabel94))
                .addGap(18, 18, 18)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(dtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel95)
                        .addGap(18, 18, 18)
                        .addComponent(dtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93)
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel94)
                    .addComponent(dtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtFechaHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel95, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel94.getAccessibleContext().setAccessibleName("desde");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(btnGenerar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        
        if(this.txtNumeroDocumento.getText().compareTo("")==0){
            JOptionPane.showMessageDialog(null,"El campo DNI esta Vacio");
            return;
        }
       // String reportSource = new File("").getAbsolutePath()+ "/src/Vista/PedidosPorCliente.jrxml";
        String reportSource = "./src/Vista/PedidosPorCliente.jrxml";
     
       
        Map<String, Object> params = new HashMap<String, Object>();
       
        try
            {   
                if (!EasyGas.sesion.isOpen()) {
                    EasyGas.sesion = EasyGas.sesFact.openSession();
                }
                Connection conn = null;
                SessionFactoryImplementor sfi = (SessionFactoryImplementor) EasyGas.sesion.getSessionFactory();
                    ConnectionProvider cp = sfi.getConnectionProvider();
                    conn = cp.getConnection();
                SimpleDateFormat formato = 
                    new SimpleDateFormat("EEEE d 'de' MMMM 'de' yyyy", new Locale("es","ES"));
                List<Cliente> clientes= clienteControlador.BuscarCliente(null, null, this.txtNumeroDocumento.getText(), "");
                Cliente c =clientes.get(0);
                String fecha = formato.format(new Date());
                params.put("NombreCliente","Nombre: " + c.getNombres() + " - DNI:  " + this.txtNumeroDocumento.getText() );
                params.put("FieldName",c.getNombres() );
                params.put("realPath","../recursos/");
                params.put("numeroDocumento",this.txtNumeroDocumento.getText());
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                String fechaDesde=dtFechaDesde.getDate()==null?"":myFormat.format(dtFechaDesde.getDate());
                String fechaHasta=dtFechaHasta.getDate()==null?"":myFormat.format(dtFechaHasta.getDate());
                String nombre =EasyGas.usuarioActual==null? "Administrador":EasyGas.usuarioActual.getEmpleado().getNombres() +  " " + EasyGas.usuarioActual.getEmpleado().getApellidoPat();
                params.put("reportTitle", "Pedidos por Cliente"); params.put("author", nombre ); params.put("fechaHasta", fechaHasta);
                params.put("fechaDesde", fechaDesde);params.put("startDate", fecha);
                
                JasperReport jasperReport =
                    JasperCompileManager.compileReport(reportSource);

                JasperPrint jasperPrint =
                    JasperFillManager.fillReport(
                        jasperReport, params,conn);
 
                JasperViewer.viewReport(jasperPrint,false);
            }

            catch (Exception ex)
            {
                ex.printStackTrace();
            }
            finally{
                if (EasyGas.sesion.isOpen()){
                    EasyGas.sesion.close();
                }
            }
  
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox cmbCamionBuscarEstado;
    private javax.swing.JComboBox cmbCamionBuscarTipo;
    private com.toedter.calendar.JDateChooser dtFechaDesde;
    private com.toedter.calendar.JDateChooser dtFechaHasta;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel41;
    private java.awt.Label label13;
    private javax.swing.JPanel panelManten;
    private javax.swing.JTextField txtCamionBuscarPlaca;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables
}
