/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import java.util.*;
import Controlador.*;
import Modelo.Hibernate.*;
import java.awt.Cursor;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author alulab14
 */
public class Pantalla_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameUsuario
     */
    UsuarioControlador usuarioControlador= new UsuarioControlador();
    EmpleadoControlador empleadoControlador= new EmpleadoControlador();
    Empleado empleado = new Empleado();
    public Pantalla_Usuario() {
        initComponents();
        List<Usuario> lista = usuarioControlador.listarUsuarios();
        usuarioControlador.actualizaTablaUsuarios(lista,this.tblUSuario);
        habilitado(true);
        
    }
    public void habilitado(boolean flag){
        this.btnBuscarEmpleado.setEnabled(flag);
        txtCorreo.setEnabled(flag);
        txtNombreUsuario.setEnabled(flag);
        this.btnUsuarioEditar.setEnabled(!flag);
        this.btnUsuarioCancelar.setEnabled(flag);
        this.btnUsuarioGuardar.setEnabled(flag);
        this.btnUsuarioEliminar.setEnabled(!flag);
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuario = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        label13 = new java.awt.Label();
        btnUsuarioGuardar = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnUSuarioNuevo = new javax.swing.JButton();
        btnUsuarioCancelar = new javax.swing.JButton();
        btnUsuarioEditar = new javax.swing.JButton();
        btnUsuarioEliminar = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        label24 = new java.awt.Label();
        jPanel59 = new javax.swing.JPanel();
        txtNombreBuscar = new javax.swing.JTextField();
        jLabel128 = new javax.swing.JLabel();
        txtDNIBuscar = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jLabel130 = new javax.swing.JLabel();
        txtNombreUsuarioBuscar = new javax.swing.JTextField();
        jLabel131 = new javax.swing.JLabel();
        cmbxPuestos = new javax.swing.JComboBox();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblUSuario = new javax.swing.JTable();
        btnUsuarioBuscar = new javax.swing.JButton();

        setResizable(true);

        panelUsuario.setBackground(new java.awt.Color(240, 240, 225));

        jPanel27.setBackground(new java.awt.Color(240, 240, 225));
        jPanel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel27.setPreferredSize(new java.awt.Dimension(400, 620));
        jPanel27.setRequestFocusEnabled(false);

        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label13.setForeground(new java.awt.Color(51, 0, 102));
        label13.setText("Usuario");

        btnUsuarioGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarioGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_guardar.png"))); // NOI18N
        btnUsuarioGuardar.setText("Guardar");
        btnUsuarioGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioGuardarActionPerformed(evt);
            }
        });

        jPanel28.setBackground(new java.awt.Color(240, 240, 225));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanel28.setPreferredSize(new java.awt.Dimension(360, 180));

        jLabel67.setText("Nombre Completo:");

        txtNombreCompleto.setEnabled(false);

        txtCodigo.setEnabled(false);

        jLabel113.setText("Código:");

        jLabel133.setText("DNI:");

        btnBuscarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_buscar.png"))); // NOI18N
        btnBuscarEmpleado.setText("Buscar Empleado");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarEmpleado))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel133)
                            .addComponent(jLabel113)
                            .addComponent(jLabel67))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNombreCompleto)
                            .addComponent(txtDNI))))
                .addGap(20, 20, 20))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel113)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel133)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnBuscarEmpleado)
                .addContainerGap())
        );

        btnUSuarioNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUSuarioNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_nuevo.png"))); // NOI18N
        btnUSuarioNuevo.setText("Nuevo");
        btnUSuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSuarioNuevoActionPerformed(evt);
            }
        });

        btnUsuarioCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarioCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_cancelar.png"))); // NOI18N
        btnUsuarioCancelar.setText("Cancelar");
        btnUsuarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioCancelarActionPerformed(evt);
            }
        });

        btnUsuarioEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_editar.png"))); // NOI18N
        btnUsuarioEditar.setText("Editar");
        btnUsuarioEditar.setEnabled(false);
        btnUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioEditarActionPerformed(evt);
            }
        });

        btnUsuarioEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarioEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_eliminar.png"))); // NOI18N
        btnUsuarioEliminar.setText("Eliminar");
        btnUsuarioEliminar.setEnabled(false);
        btnUsuarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioEliminarActionPerformed(evt);
            }
        });

        jPanel29.setBackground(new java.awt.Color(240, 240, 225));
        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));

        jLabel68.setText("Correo:");

        jLabel69.setText("Nombre Usuario:");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69)
                    .addComponent(jLabel68))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addGap(20, 20, 20))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(btnUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(btnUsuarioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUSuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUSuarioNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarioEliminar)
                    .addComponent(btnUsuarioEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarioGuardar)
                    .addComponent(btnUsuarioCancelar))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel58.setBackground(new java.awt.Color(240, 240, 225));
        jPanel58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel58.setPreferredSize(new java.awt.Dimension(750, 620));
        jPanel58.setRequestFocusEnabled(false);

        label24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label24.setForeground(new java.awt.Color(51, 0, 102));
        label24.setText("Buscar Usuario");

        jPanel59.setBackground(new java.awt.Color(240, 240, 225));
        jPanel59.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanel59.setPreferredSize(new java.awt.Dimension(340, 120));

        jLabel128.setText("Nombre:");

        jLabel129.setText("DNI:");

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel59Layout.createSequentialGroup()
                        .addComponent(jLabel128)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel59Layout.createSequentialGroup()
                        .addComponent(jLabel129)
                        .addGap(18, 18, 18)
                        .addComponent(txtDNIBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel128))
                .addGap(18, 18, 18)
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNIBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel129))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel61.setBackground(new java.awt.Color(240, 240, 225));
        jPanel61.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));
        jPanel61.setPreferredSize(new java.awt.Dimension(340, 120));

        jLabel130.setText("Puesto:");

        jLabel131.setText("Nombre:");

        cmbxPuestos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Chofer", "Despechador", "Asistente" }));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel61Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel61Layout.createSequentialGroup()
                        .addComponent(jLabel131)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel61Layout.createSequentialGroup()
                        .addComponent(jLabel130)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbxPuestos, 0, 250, Short.MAX_VALUE)
                    .addComponent(txtNombreUsuarioBuscar))
                .addContainerGap())
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel61Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel131))
                .addGap(18, 18, 18)
                .addGroup(jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel130)
                    .addComponent(cmbxPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblUSuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(32), "Mary Vega", "34874563", null, null},
                { new Integer(254), "Pablo Morales", "65475676", null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "DNI", "Usuario", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUSuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUSuarioMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tblUSuario);
        if (tblUSuario.getColumnModel().getColumnCount() > 0) {
            tblUSuario.getColumnModel().getColumn(0).setResizable(false);
            tblUSuario.getColumnModel().getColumn(1).setResizable(false);
            tblUSuario.getColumnModel().getColumn(2).setResizable(false);
            tblUSuario.getColumnModel().getColumn(3).setResizable(false);
            tblUSuario.getColumnModel().getColumn(4).setResizable(false);
        }

        btnUsuarioBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarioBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_buscar.png"))); // NOI18N
        btnUsuarioBuscar.setText("Buscar");
        btnUsuarioBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel58Layout.createSequentialGroup()
                        .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel58Layout.createSequentialGroup()
                        .addComponent(label24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)
                        .addComponent(btnUsuarioBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20))
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarioBuscar))
                .addGap(20, 20, 20)
                .addGroup(jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioBuscarActionPerformed
        // TODO add your handling code here:
       
        habilitado(false);
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        List<Usuario> lista = usuarioControlador.buscaUsuarioFiltro(txtDNIBuscar.getText() ,txtNombreBuscar.getText(),cmbxPuestos.getSelectedItem().toString(),txtNombreUsuarioBuscar.getText());
        usuarioControlador.actualizaTablaUsuarios(lista,this.tblUSuario);
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnUsuarioBuscarActionPerformed

    private void tblUSuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUSuarioMouseClicked
        if (evt.getSource() == tblUSuario){
            habilitado(false);
            txtDNI.setEnabled(false);
            int fila = tblUSuario.getSelectedRow();
            VerDatos(tblUSuario.getValueAt(fila, 0).toString());

        }
    }//GEN-LAST:event_tblUSuarioMouseClicked

    private void btnUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioEliminarActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar el registro?");
        if(confirma==0){
            int id = Integer.parseInt(txtCodigo.getText());
            String mensaje = usuarioControlador.EliminarUsuario(id);
            JOptionPane.showMessageDialog(null, mensaje);
            habilitado(true);
            txtNombreUsuario.setText("");
            txtNombreCompleto.setText("");
            txtDNI.setText("");
            txtCorreo.setText("");
            txtCodigo.setText("");
            List<Usuario> lista = usuarioControlador.listarUsuarios();
            usuarioControlador.actualizaTablaUsuarios(lista,this.tblUSuario);
        }
    }//GEN-LAST:event_btnUsuarioEliminarActionPerformed

    private void btnUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioEditarActionPerformed
        // TODO add your handling code here:
        habilitado(true);
        this.btnBuscarEmpleado.setEnabled(false);
    }//GEN-LAST:event_btnUsuarioEditarActionPerformed

    private void btnUsuarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioCancelarActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que no desea guardar los cambios");
        if(confirmacion==0){
            VerDatos(txtCodigo.getText());
            habilitado(false);
        }
    }//GEN-LAST:event_btnUsuarioCancelarActionPerformed

    private void btnUSuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSuarioNuevoActionPerformed
        habilitado(true);
        txtDNI.setEnabled(true);
        txtNombreUsuario.setText("");
        txtNombreCompleto.setText("");
        txtDNI.setText("");
        txtCorreo.setText("");
        txtCodigo.setText("");

    }//GEN-LAST:event_btnUSuarioNuevoActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed

        String mensaje="";
        if(!((mensaje=validar(txtDNI.getText(),"DNI",8,8,"d")).compareTo("")== 0)) {
            JOptionPane.showMessageDialog(null,mensaje);
            return;
        }
        else {
            if ((empleado=empleadoControlador.obtenerEmpleadoPorDNI(txtDNI.getText()))==null){
                mensaje="EL DNI no pertenece a ningun Empleado";
                JOptionPane.showMessageDialog(null,mensaje);
                return;
            }
            else {
                Usuario usuarioPrueba = usuarioControlador.obtenerUsuarioPorIdEmpleado(empleado.getIdEmpleado());
                if(usuarioPrueba==null){
                    txtNombreCompleto.setText(empleado.getNombres()+ " " + empleado.getApellidoPat() + " " +empleado.getApellidoMat());
                    
                }
                else {
                    mensaje="EL DNI ya tiene una cuenta";
                    JOptionPane.showMessageDialog(null,mensaje);
                    return;

                }
            }

        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnUsuarioGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioGuardarActionPerformed
        //validar campos vacios
         int confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que desea guardar los cambios");
            if(confirmacion==0){
                 Usuario u=null;
            String mensaje="";
            if (!(txtCodigo.getText().compareTo("")==0)){
                // es actualizacion
                u=usuarioControlador.obtenerUsuarioPorCodigo(Integer.parseInt(txtCodigo.getText()));
            }
            if(!((mensaje=validar(txtCorreo.getText(),"Correo",5,50,"s")).compareTo("")== 0)) {
                JOptionPane.showMessageDialog(null,mensaje);
                return;
            }
            else {
                if (!esValidoCorreo(txtCorreo.getText())){
                    mensaje="El campo correo no tiene el formato correcto";
                    JOptionPane.showMessageDialog(null,mensaje);
                    return;
                }
                else {
                    if (( (txtCodigo.getText().compareTo("")==0)  || !((u.getCorreo().compareTo(txtCorreo.getText())==0))) && usuarioControlador.existeCorreo(txtCorreo.getText())){
                        mensaje="El correo ya ha sido registrado";
                        JOptionPane.showMessageDialog(null,mensaje);
                        return;
                    }

                }
            }

            if(!((mensaje=validar(txtNombreUsuario.getText(),"Nombre Usuario",5,15,"s")).compareTo("")== 0)) {
                JOptionPane.showMessageDialog(null,mensaje);
                return;
            }

            else {
                if ( ((txtCodigo.getText().compareTo("")==0) || !(u.getNombreUsuario().compareTo(txtNombreUsuario.getText())==0)) && usuarioControlador.existeNombreUsuario(txtNombreUsuario.getText(),"registro") ){
                    mensaje="El nombre de usuario ya existe";
                    JOptionPane.showMessageDialog(null,mensaje);
                    return;
                }

            }

            usuarioControlador.guardarUsuario(txtNombreUsuario.getText(),txtCorreo.getText(),empleado,txtCodigo.getText());

            mensaje = "Se guardaron los cambios exitosamente";
            List<Usuario> lista = usuarioControlador.listarUsuarios();
            usuarioControlador.actualizaTablaUsuarios(lista,this.tblUSuario);
            JOptionPane.showMessageDialog(null,mensaje);
        }
       

    }//GEN-LAST:event_btnUsuarioGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtDNIBuscar.setText("");
        txtNombreBuscar.setText("");
        cmbxPuestos.setSelectedIndex(0);
        txtNombreUsuarioBuscar.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private  boolean esValidoCorreo(String correo) {
        boolean result = true;
        try {
           InternetAddress correoAd = new InternetAddress(correo);
           correoAd.validate();
        } catch (AddressException ex) {
           result = false;
        }
        return result;
    }    
    private String validar(String campo, String nombreCampo,int minCaracteres , int maxCaracteres ,String formato){
        // formato=d (numerico) formato=s solo cadenas
        
        String mensaje="";
        String regex = "[0-9]*"; 
        if (campo.compareTo("")== 0) {
            mensaje="El campo " + nombreCampo + " esta vacio";
            return mensaje;
        } 
        else{
            if (formato.compareTo("s")== 0) {
                if(campo.matches(regex)){
                    mensaje="El campo "+ nombreCampo + " solo debe contener letras";
                    return mensaje;
                }
                else{
                    if(!(maxCaracteres>=campo.length() && minCaracteres<=campo.length())) {
                        if(maxCaracteres==minCaracteres) mensaje="El campo " + nombreCampo + " debe de tener " + maxCaracteres + " caracteres" ;
                        else mensaje="El campo " + nombreCampo + " debe de tener entre " + minCaracteres + " y " + maxCaracteres + " caracteres";
                        return mensaje;
                    }
                }
            } else {
                
                if(!campo.matches(regex)){
                    mensaje="El campo "+ nombreCampo + " solo debe contener digitos";
                    return mensaje;
                }
                else{
                    if(!(maxCaracteres>=campo.length() && minCaracteres<=campo.length())) {
                        if(maxCaracteres==minCaracteres) mensaje="El campo " + nombreCampo + " debe de tener " + maxCaracteres + " caracteres" ;
                        else mensaje="El campo " + nombreCampo + " debe de tener entre " + minCaracteres + " y " + maxCaracteres + " caracteres";
                        return mensaje;
                    }
                }
                
            
            }
        } 
        return mensaje;
    }
    private void VerDatos(String strCodigo){    
        int idUsuarioSeleccionado = Integer.parseInt(strCodigo);
        Usuario usuario = usuarioControlador.obtenerUsuarioPorCodigo(idUsuarioSeleccionado);
        txtNombreCompleto.setText(usuario.getEmpleado().getNombres() + " " + usuario.getEmpleado().getApellidoPat() + " " + usuario.getEmpleado().getApellidoMat() );
        txtCorreo.setText(usuario.getCorreo());
        txtNombreUsuario.setText(usuario.getNombreUsuario());
        txtDNI.setText(usuario.getEmpleado().getDni());
        txtCodigo.setText(usuario.getIdUsuario().toString());
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnUSuarioNuevo;
    private javax.swing.JButton btnUsuarioBuscar;
    private javax.swing.JButton btnUsuarioCancelar;
    private javax.swing.JButton btnUsuarioEditar;
    private javax.swing.JButton btnUsuarioEliminar;
    private javax.swing.JButton btnUsuarioGuardar;
    private javax.swing.JComboBox cmbxPuestos;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JScrollPane jScrollPane12;
    private java.awt.Label label13;
    private java.awt.Label label24;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTable tblUSuario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNIBuscar;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNombreUsuarioBuscar;
    // End of variables declaration//GEN-END:variables
}
