/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.TipoCamionControlador;
import Modelo.Hibernate.TipoCamion;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 * Version: 1.1
 * Ultima Modificacion: 23/10/2015
 * Descripcion del Cambio: 
 * Autor: Miriam Encarnacion
 */

public class Pantalla_TipoCamion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameTipoCamion
     */
    
    private TipoCamionControlador tpCamionControlador = new TipoCamionControlador();
    private TipoCamionModelo tpCamionModelo = new TipoCamionModelo();
    private EventoTabla eventoTbl= new EventoTabla() ;
        
    public Pantalla_TipoCamion() {
        initComponents();
        tblTipoCamion.setModel(tpCamionModelo);
        panelTipoCamion.addMouseListener(eventoTbl);
        tblTipoCamion.addMouseListener(eventoTbl);
        RefrescarTablaTipoCamion();
    }    
        
    /**
     * Refresca la tabla
     */   
    private void RefrescarTablaTipoCamion(){
        tpCamionModelo.listaTipoCamion = tpCamionControlador.ListarTipoCamion();
        tpCamionModelo.fireTableChanged(null);
    }
    
    /**
    * Modelo de la tabla para poder manejarla facilmente
    */
    private class TipoCamionModelo extends AbstractTableModel{
        
	List<TipoCamion> listaTipoCamion = null;
	String [] titles = {"Código", "Nombre", "GLP", "Diesel", "Tara"};
	
        @Override
	public int getColumnCount() {
            // TODO Auto-generated method stub
            return titles.length;
	}
	@Override
	public int getRowCount() {
            // TODO Auto-generated method stub
            return listaTipoCamion.size();
	}
	@Override
	public Object getValueAt(int rowIndex, int columnIndex) {
            // TODO Auto-generated method stub
            TipoCamion tc = listaTipoCamion.get(rowIndex);
            String value = "";
            switch(columnIndex){
                case 0: value = tc.getIdTipoCamion().toString(); break;
                case 1: value = tc.getNombre(); break;
                case 2: value = ""+ tc.getCapacidadGlp(); break; 
                case 3: value = ""+ tc.getCapacidadDiesel(); break; 
                case 4: value = ""+ tc.getTara(); break; 
            }
            return value;
        }
	@Override	
	public String getColumnName(int col){
            return titles[col];
	}
    }

    /**
     * Manejedor de eventos
     */
    private class EventoTabla implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent evt) {            
            if (evt.getSource() == tblTipoCamion){                
                int fila = tblTipoCamion.getSelectedRow();
                VerDatos(tblTipoCamion.getValueAt(fila, 0).toString());
                DatosEditables(false);
                BotonesEditables(false);
            }
        }

        @Override
        public void mouseEntered(MouseEvent arg0) {
            // TODO Auto-generated method stub
            //label25.setText("Entered");
        }

        @Override
        public void mouseExited(MouseEvent arg0) {
            // TODO Auto-generated method stub
            //label25.setText("Exited");
        }

        @Override
        public void mousePressed(MouseEvent arg0) {
            // TODO Auto-generated method stub
            //label25.setText("Pressed");
        }

        @Override
        public void mouseReleased(MouseEvent arg0) {
            // TODO Auto-generated method stub
            //label25.setText("Released");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTipoCamion = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        label16 = new java.awt.Label();
        jPanel36 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        txtTipoCamionCodigo = new javax.swing.JTextField();
        txtTipoCamionNombre = new javax.swing.JTextField();
        spnTipoCamionGLP = new javax.swing.JSpinner();
        spnTipoCamionDiesel = new javax.swing.JSpinner();
        spnTipoCamionTara = new javax.swing.JSpinner();
        btnTipoCamionNuevo = new javax.swing.JButton();
        btnTipoCamionEliminar = new javax.swing.JButton();
        btnTipoCamionEditar = new javax.swing.JButton();
        btnTipoCamionCancelar = new javax.swing.JButton();
        btnTipoCamionGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label25 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoCamion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        panelTipoCamion.setBackground(new java.awt.Color(240, 240, 225));

        jPanel33.setBackground(new java.awt.Color(240, 240, 225));
        jPanel33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel33.setPreferredSize(new java.awt.Dimension(400, 620));

        label16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label16.setForeground(new java.awt.Color(51, 0, 102));
        label16.setText("Tipo Camión");

        jPanel36.setBackground(new java.awt.Color(240, 240, 225));
        jPanel36.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel36.setPreferredSize(new java.awt.Dimension(360, 220));

        jLabel77.setText("Nombre:");

        jLabel78.setText("Capacidad GLP (Ton):");

        jLabel84.setText("Capacidad Diesel (Gal):");

        jLabel132.setText("Tara (Ton):");

        jLabel82.setText("Código:");

        txtTipoCamionCodigo.setEnabled(false);

        txtTipoCamionNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoCamionNombreKeyTyped(evt);
            }
        });

        spnTipoCamionGLP.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        spnTipoCamionDiesel.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        spnTipoCamionTara.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel84)
                    .addComponent(jLabel78)
                    .addComponent(jLabel77)
                    .addComponent(jLabel132)
                    .addComponent(jLabel82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTipoCamionCodigo)
                    .addComponent(txtTipoCamionNombre)
                    .addComponent(spnTipoCamionDiesel)
                    .addComponent(spnTipoCamionGLP)
                    .addComponent(spnTipoCamionTara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(txtTipoCamionCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(txtTipoCamionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(spnTipoCamionGLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(spnTipoCamionDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel132)
                    .addComponent(spnTipoCamionTara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        btnTipoCamionNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoCamionNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_nuevo.png"))); // NOI18N
        btnTipoCamionNuevo.setText("Nuevo");
        btnTipoCamionNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCamionNuevoActionPerformed(evt);
            }
        });

        btnTipoCamionEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoCamionEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_eliminar.png"))); // NOI18N
        btnTipoCamionEliminar.setText("Eliminar");
        btnTipoCamionEliminar.setEnabled(false);
        btnTipoCamionEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCamionEliminarActionPerformed(evt);
            }
        });

        btnTipoCamionEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoCamionEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_editar.png"))); // NOI18N
        btnTipoCamionEditar.setText("Editar");
        btnTipoCamionEditar.setEnabled(false);
        btnTipoCamionEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCamionEditarActionPerformed(evt);
            }
        });

        btnTipoCamionCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoCamionCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_cancelar.png"))); // NOI18N
        btnTipoCamionCancelar.setText("Cancelar");
        btnTipoCamionCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCamionCancelarActionPerformed(evt);
            }
        });

        btnTipoCamionGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoCamionGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img_guardar.png"))); // NOI18N
        btnTipoCamionGuardar.setText("Guardar");
        btnTipoCamionGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoCamionGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(btnTipoCamionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addComponent(btnTipoCamionCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTipoCamionGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addComponent(btnTipoCamionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTipoCamionEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipoCamionNuevo))
                .addGap(20, 20, 20)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoCamionEliminar)
                    .addComponent(btnTipoCamionEditar))
                .addGap(18, 18, 18)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoCamionGuardar)
                    .addComponent(btnTipoCamionCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(240, 240, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 620));

        label25.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label25.setForeground(new java.awt.Color(51, 0, 102));
        label25.setText("Lista de Tipos de Camión");

        tblTipoCamion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo", "Cantidad GLP (Ton)", "Cantidad Diesel (Gal)", "Tara (Ton)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTipoCamion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTipoCamionLayout = new javax.swing.GroupLayout(panelTipoCamion);
        panelTipoCamion.setLayout(panelTipoCamionLayout);
        panelTipoCamionLayout.setHorizontalGroup(
            panelTipoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoCamionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoCamionLayout.setVerticalGroup(
            panelTipoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoCamionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTipoCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTipoCamion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTipoCamion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerDatos(String strCodigo){    
        int idTipoCamionSel = Integer.parseInt(strCodigo);
        TipoCamion tp = tpCamionControlador.BuscarTipoCamionPorCodigo(idTipoCamionSel);
        txtTipoCamionCodigo.setText("" + tp.getIdTipoCamion());
        txtTipoCamionNombre.setText(tp.getNombre());
        spnTipoCamionGLP.setValue(tp.getCapacidadGlp());
        spnTipoCamionDiesel.setValue(tp.getCapacidadDiesel());
        spnTipoCamionTara.setValue(tp.getTara());
    }
    
    private void DatosEditables(boolean valor){
        txtTipoCamionNombre.setEnabled(valor);
        spnTipoCamionGLP.setEnabled(valor);
        spnTipoCamionDiesel.setEnabled(valor);
        spnTipoCamionTara.setEnabled(valor);
    }
    
    private void BotonesEditables(boolean valor){
        btnTipoCamionNuevo.setEnabled(!valor);
        btnTipoCamionEliminar.setEnabled(!valor);
        btnTipoCamionEditar.setEnabled(!valor);
        btnTipoCamionCancelar.setEnabled(valor);
        btnTipoCamionGuardar.setEnabled(valor);
    }
    
    private void btnTipoCamionNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCamionNuevoActionPerformed
        txtTipoCamionCodigo.setText("");
        txtTipoCamionNombre.setText("");
        spnTipoCamionGLP.setValue(0);
        spnTipoCamionDiesel.setValue(0);
        spnTipoCamionTara.setValue(0);        
        DatosEditables(true);
        BotonesEditables(true);
    }//GEN-LAST:event_btnTipoCamionNuevoActionPerformed

    private void btnTipoCamionEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCamionEliminarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el registro");
        if (confirmacion== 0){           
            String strCodigo = txtTipoCamionCodigo.getText();
            int codigo = Integer.parseInt(strCodigo);
            String mensaje = tpCamionControlador.EliminarTipoCamion(codigo);
            JOptionPane.showMessageDialog(null, mensaje);
            RefrescarTablaTipoCamion();
            txtTipoCamionCodigo.setText("");
            txtTipoCamionNombre.setText("");
            spnTipoCamionGLP.setValue(0);
            spnTipoCamionDiesel.setValue(0);
            spnTipoCamionTara.setValue(0);  
            DatosEditables(true);
            BotonesEditables(true);
        }
    }//GEN-LAST:event_btnTipoCamionEliminarActionPerformed

    private void btnTipoCamionEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCamionEditarActionPerformed
        DatosEditables(true);
        BotonesEditables(true);
    }//GEN-LAST:event_btnTipoCamionEditarActionPerformed

    private void btnTipoCamionCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCamionCancelarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que no desea guardar los cambios");
        if (confirmacion== 0){ 
            VerDatos(txtTipoCamionCodigo.getText());
            DatosEditables(false);
            BotonesEditables(false);
        }         
    }//GEN-LAST:event_btnTipoCamionCancelarActionPerformed

    private void btnTipoCamionGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoCamionGuardarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que desea guardar los cambios");
        if (confirmacion== 0){ 
            TipoCamion tp = new TipoCamion();
            String strCodigo = txtTipoCamionCodigo.getText();
            tp.setNombre(txtTipoCamionNombre.getText());
            tp.setCapacidadGlp((int)spnTipoCamionGLP.getValue());
            tp.setCapacidadDiesel((int)spnTipoCamionDiesel.getValue());
            tp.setTara((int)spnTipoCamionTara.getValue());

            // Nuevo Registro de Tipo Camion
            if (strCodigo.equals("")){
                int verifica = tpCamionControlador.GuardarTipoCamion(tp);
                if (verifica==1){
                    DatosEditables(false);
                    BotonesEditables(false);
                    RefrescarTablaTipoCamion();
                }                
            }
            // Actualizacion de Registro de Tipo Camion
            else {
                tp.setIdTipoCamion(Integer.parseInt(strCodigo));
                int verifica = tpCamionControlador.ActualizarTipoCamion(tp);
                if (verifica==1){
                    DatosEditables(false);
                    BotonesEditables(false);
                    RefrescarTablaTipoCamion();
                } 
            }
        }      
    }//GEN-LAST:event_btnTipoCamionGuardarActionPerformed

    private void txtTipoCamionNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoCamionNombreKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (txtTipoCamionNombre.getText().length() > 20) {
            evt.consume();
        }
        if (!(car >= 'a' && car <= 'z') && !(car >= 'A' && car <= 'Z') && (car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTipoCamionNombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTipoCamionCancelar;
    private javax.swing.JButton btnTipoCamionEditar;
    private javax.swing.JButton btnTipoCamionEliminar;
    private javax.swing.JButton btnTipoCamionGuardar;
    private javax.swing.JButton btnTipoCamionNuevo;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label16;
    private java.awt.Label label25;
    private javax.swing.JPanel panelTipoCamion;
    private javax.swing.JSpinner spnTipoCamionDiesel;
    private javax.swing.JSpinner spnTipoCamionGLP;
    private javax.swing.JSpinner spnTipoCamionTara;
    private javax.swing.JTable tblTipoCamion;
    private javax.swing.JTextField txtTipoCamionCodigo;
    private javax.swing.JTextField txtTipoCamionNombre;
    // End of variables declaration//GEN-END:variables
}
